name: 'Create Branch From Specific Hash'
description: 'Create Branch From Specific Hash'
author: 'Satyabrata Swain (satyabrata.swain@500apps.com)'
branding:
  icon: 'git-branch' 
  color: 'black'
inputs:
  branch:
    description: 'The branch to create'
    default: 'release'
  from_tag:
    description: 'Provide the tag numver ex:- v0.0.7'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
